version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Monta tu archivo SQL en la carpeta correcta
      
networks:
  db-network:
    driver: bridge