version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ephy
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: web-hacking
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge